name: Check Open Classes

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Download binary from release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release download --repo ${{ github.repository }} -p 'neis-tools' --clobber

      - name: Make binary executable
        run: chmod +x neis-tools

      - name: Run scraper
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_URL_FOR_ERROR: ${{ secrets.SLACK_WEBHOOK_URL_FOR_ERROR }}
        run: ./neis-tools
